# Generated by Django 4.2.11 on 2024-06-04 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('Address', models.CharField(max_length=600)),
                ('Gender', models.CharField(max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Skills', models.CharField(max_length=900)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='work_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('projects', models.CharField(max_length=900)),
                ('position', models.CharField(max_length=200)),
                ('certificates', models.ImageField(upload_to='certificate/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.user_profile')),
            ],
        ),
    ]
