# Generated by Django 4.2.11 on 2024-06-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_login_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='cpass',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='password',
        ),
    ]
