# Generated by Django 4.2.11 on 2024-06-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_remove_user_profile_cpass_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='username',
        ),
    ]
