# Generated by Django 4.2.11 on 2024-06-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_rename_name_user_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_details',
            old_name='user',
            new_name='userid',
        ),
    ]
