# Generated by Django 4.2.11 on 2024-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_rename_user_work_details_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('Address', models.CharField(max_length=600)),
                ('Gender', models.CharField(max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Skills', models.CharField(max_length=900)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('company', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('projects', models.CharField(max_length=900)),
                ('position', models.CharField(max_length=200)),
                ('certificates', models.ImageField(upload_to='certificate/')),
            ],
        ),
        migrations.RemoveField(
            model_name='work_details',
            name='userid',
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
        migrations.DeleteModel(
            name='work_details',
        ),
    ]
