# Generated by Django 4.2.11 on 2024-06-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_user_details_remove_work_details_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
