# Generated by Django 4.2.11 on 2024-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_alter_user_details_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='certificates',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
