# Generated by Django 4.2.11 on 2024-06-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_alter_user_details_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='certificates',
            field=models.CharField(default=1234, max_length=1200),
            preserve_default=False,
        ),
    ]
